---
- name: Add Bitnami Helm repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Install Nginx
  kubernetes.core.helm:
    name: nginx
    chart_ref: bitnami/nginx
    release_namespace: default
